### ISSUE TITLE
Une erreur au hasard

### ISSUE THREAD

**Issue by rigobert9** [Wiibleyde/concoursNsi#1]
Je n'ai pas compris comment jouer au jeu, mais j'ai tenu à l'esssayer en tant que concurrent au concours. Je suis tombé sur cette erreur, après avoir croisé l'un des monstres en haut à droite sur la carte.
```traceback
Traceback (most recent call last):
  File "/home/rigobert9/Desktop/1/trophees-nsi-2022/source/main.py", line 215, in <module>
    for d in current_level.get_drawable (current_level.get_player ().get_pos ()) :
  File "/home/rigobert9/Desktop/1/trophees-nsi-2022/source/level.py", line 217, in get_drawable
    return [i for i in self.hiden_environment if self.dicover[i.get_pos ()]] + [i for i in self.environment if i.get_pos () in player_vision] + self.bosses + self.vags + [self.player] # !CHANGE!
  File "/home/rigobert9/Desktop/1/trophees-nsi-2022/source/level.py", line 217, in <listcomp>
    return [i for i in self.hiden_environment if self.dicover[i.get_pos ()]] + [i for i in self.environment if i.get_pos () in player_vision] + self.bosses + self.vags + [self.player] # !CHANGE!
KeyError: (98, 15)
```
Bon debug, et bonne chance à vous !

**Comment by Wiibleyde** [comment]
Yeah, thx, but this project is finished and we returned it. 😉
So... It's too late 😭.

Le mer. 24 août 2022, 18:52, François Gallois ***@***.***> a
écrit :
